### PR TITLE
Update EbaySynchronizer.php

### PR DESCRIPTION
**Pull request by bumarius**
remove comma at the end of return array 'titleTemplate' => $ebay_profile->getConfiguration('EBAY_PRODUCT_TEMPLATE_TITLE')

marius

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @bumarius,

Leaving the latest comma is not a problem with PHP.

Does it throw errors on your server ?

**Comment by bumarius** [comment]
hello,

no there is not a problem.

I'm searching why when I make a product update in prestashop the result in my ebay store is strange.

all the 
    DESCRIPTION SHORT becomes Array
    DESCRIPTION becomes Array
    PRODUCT_NAME becomes Array

So I lose DESCRIPTION SHORT, DESCRIPTION et PRODUCT_NAME variable in the way
If I'm going to the backend module and if I use the synchronization button all the products are again fine in ebay store.

but nothing related with the comma. :)

marius

**Comment by thoma202** [comment]
Hi, 

This is currently under investigation. The problems comes when user is in multishop and the hook UpdateProduct is called. 
This should be solved in the next release.

**Comment by thoma202** [comment]
This PR can be closed the problem has been fixed : 
https://github.com/thoma202/ebay/commit/390c0e82fb8a5f4774511ddba12b985e9834914c

**Pull request closed without merging**
