### PR TITLE
Release/1.11.0

### PR DESCRIPTION
**Pull request by thoma202**
Release 1.11 adds : 

- Screen to help merchant understand behavior (visualisations > Orphan products / Prestashop Catalog) 
- Redesign of categories' screen
- Bug fix on ebay_user length
- Bug fix on CDATA for images send in XML
- Added warning concerning CRON Task

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

When I try to checkout your changes, I have conflicts on the following files:
```sh
	modifié des deux côtés :  classes/EbayProductModified.php
	modifié des deux côtés :  classes/EbayStoreCategory.php
	modifié des deux côtés :  classes/EbaySynchronizer.php
	modifié des deux côtés :  ebay.php
```

Can you please check that your fork is up to date with the origin repository ?
Thanks

**Comment by thoma202** [comment]
Hi @Quetzacoalt91 

I've just merged the master branche from PrestaShop and fixed the issues :) 
It should be ok now

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

The file *views/templates/hook/formTemplateManager.tpl.orig* can be removed.
I'm still reviewing the pull-request meanwhile.

**Comment by Quetzacoalt91** [comment]
Hi,

Trying to remove an incomplete ebay profile does not work, and I cannot try to link it again (An alert appears, saying the profile already exists).

I guess the JavaScript supposed to delete a profile does not work, and prevents me to manage my accounts.

**Comment by thoma202** [comment]
Hi @Quetzacoalt91 

The file has been removed. 

We had already seen the bug and decided to do it in release R1 (next release of the module that should be out mid-August). 

Thoma

**Comment by Quetzacoalt91** [comment]
Hi,

Hope this will be fixed very soon, because the module could not be used on my cloud shop after that.
Anyway, let me know when you want to push this PR.

Best regards

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

Thanks, I have just merged your PR with the one from contributors.
The new version will be available from tomorrow.

Best regards

**Pull request merged**
